version: '3.8'

services:
  shelter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Polly1990
      - DB_NAME=Animal_Shelter
    

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=Polly1990
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./pkg/shelter/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:Polly1990@localhost:5432/Animal_Shelter?sslmode=disable", "up"]
    depends_on:
      - db

volumes:
  pgdata:


